// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siqtqfmkiwvpvlffbpaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpcXRxZm1raXd2cHZsZmZicGFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODI0OTgsImV4cCI6MjA2NzQ1ODQ5OH0.5Oo-cy_PCaOIH8yIDYMVoo6jI0dOO18RHbhcbT6AIjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});